"""Mac-side replay helper for the e2e harness (Task 4.1).

The "Mac-side replay" called for in the mega-plan is satisfied by replaying a capture
through the decode → ingest path: ``fixtures/hist_biometric.bin`` is a stream of char-05
DATA notifications written back-to-back (762 type-47 V24 records). The committed fixture
is SYNTHETIC — generated by ``scripts/gen_synthetic_fixtures.historical_v24`` with
obviously-fake biometric values — so no real on-device data is published; it is byte-for-
byte protocol-valid, so it exercises the exact same decode path as a real capture. BLE
fragments are contiguous in the file, so a sequential length-walk reassembles complete
frames — the exact proven logic from ``re/verify_v24.py``'s ``walk_frames``.
"""
import os
import struct
import zlib

from whoop_protocol import crc8, parse_frame
from whoop_protocol.interpreter import extract_historical_streams

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "hist_biometric.bin")


def walk_frames(buf: bytes):
    """Yield each complete framed packet ``[0xAA][len u16 LE][crc8(len)][type][seq][cmd]
    [data...][crc32 LE]`` from a back-to-back capture. At each position require the SOF,
    a sane length, and BOTH the crc8(len) header check and the crc32 trailer to validate;
    on any failure slip forward one byte (mirrors re/verify_v24.py)."""
    i, n = 0, len(buf)
    while i + 4 < n:
        if buf[i] != 0xAA:
            i += 1
            continue
        length = struct.unpack_from("<H", buf, i + 1)[0]
        if length < 4 or i + length + 4 > n:
            i += 1
            continue
        if crc8(buf[i + 1:i + 3]) != buf[i + 3]:
            i += 1
            continue
        pkt = buf[i + 4:i + length]
        exp = struct.unpack_from("<L", buf, i + length)[0]
        if (zlib.crc32(pkt) & 0xFFFFFFFF) != exp:
            i += 1
            continue
        yield buf[i:i + length + 4]
        i += length + 4


def decode_capture(path: str = FIXTURE) -> dict:
    """Load the real capture, reassemble + parse frames, keep type-47 HISTORICAL_DATA,
    and project them into the stream dict that /v1/ingest-decoded accepts.

    The V24 records carry their own real ``unix`` timestamp, so the device/wall clock
    refs are irrelevant for type-47 — pass 0/0 (mirrors tests/test_historical_v24.py)."""
    with open(path, "rb") as fh:
        buf = fh.read()
    parsed = []
    for frame in walk_frames(buf):
        pr = parse_frame(frame)
        if pr.get("type_name") == "HISTORICAL_DATA":
            parsed.append(pr)
    streams = extract_historical_streams(parsed, device_clock_ref=0, wall_clock_ref=0)
    return {"n_frames": len(parsed), "streams": streams}
