"""Task 4.1 — end-to-end integration test harness (needs Docker/Timescale).

Replays a SYNTHETIC capture (``fixtures/hist_biometric.bin`` — 762 protocol-valid type-47
V24 records generated by ``scripts/gen_synthetic_fixtures``) through the full server
pipeline:

    decode (Mac-side replay)  →  /v1/ingest-decoded  →  /v1/compute-daily
                              →  /v1/daily + /v1/sleep (coherence)
                              →  /v1/summary (reconciliation: no drop)
                              →  re-ingest + re-compute (idempotency: no dup)

The "Mac-side replay" of the mega-plan is satisfied by ``tests/_replay.py``'s
``decode_capture`` (sequential frame walk identical to ``re/verify_v24.py``).

Reconciliation note: the decoded stream lists contain MORE rows than land in the DB,
because the on-device store samples sub-second but the persisted natural keys are
``(device_id, ts)`` (and ``(device_id, ts, rr_ms)`` for R-R) at 1s resolution. Records
that share a key upsert IN PLACE — that is the documented dedup, not a drop. So "no
drop" is asserted against the count of DISTINCT natural keys in the decoded streams,
which must EXACTLY equal the persisted per-stream counts.
"""
import datetime as _dt
import importlib

import psycopg
import pytest
from fastapi.testclient import TestClient

from tests._replay import decode_capture
from tests.conftest import requires_docker

DEVICE = "devE2E"


@pytest.fixture
def client(clean_db, tmp_path, monkeypatch):
    monkeypatch.setenv("WHOOP_API_KEY", "secret")
    monkeypatch.setenv("WHOOP_DB_DSN", clean_db)
    monkeypatch.setenv("WHOOP_RAW_ROOT", str(tmp_path))
    import app.main as m
    importlib.reload(m)
    return TestClient(m.app, headers={"Authorization": "Bearer secret"})


# Natural-key projector: collapse a decoded stream to the distinct keys that the DB
# upsert preserves, so the expected persisted count is computed the same way the DB does.
def _distinct_keys(kind: str, rows: list) -> set:
    if kind == "rr":
        return {(r["ts"], r["rr_ms"]) for r in rows}
    if kind == "events":
        return {(r["ts"], r["kind"]) for r in rows}
    # hr / spo2 / skin_temp / resp / gravity / battery: keyed on (device_id, ts)
    return {r["ts"] for r in rows}


def _utc_dates_spanned(streams: dict) -> list:
    ts = [r["ts"] for rows in streams.values() for r in rows if r.get("ts")]
    days = {_dt.datetime.fromtimestamp(t, _dt.timezone.utc).date() for t in ts}
    return sorted(days)


@requires_docker
def test_e2e_real_capture_pipeline(client, clean_db):
    # ── 1. Decode the real capture (Mac-side replay) ──────────────────────────
    cap = decode_capture()
    streams = cap["streams"]
    assert cap["n_frames"] == 762, f"expected 762 type-47 frames, got {cap['n_frames']}"
    # Sane volumes: it's a 762-record capture; HR drops a few hr==0 startup samples.
    assert len(streams["hr"]) > 100, f"too few HR samples decoded: {len(streams['hr'])}"
    assert len(streams["spo2"]) > 100, f"too few SpO2 samples decoded: {len(streams['spo2'])}"
    assert len(streams["gravity"]) > 100, f"too few gravity samples decoded: {len(streams['gravity'])}"

    spanned = _utc_dates_spanned(streams)
    assert spanned, "decoded streams carried no usable timestamps"
    lo, hi = spanned[0], spanned[-1]

    # Expected persisted counts = distinct natural keys per stream.
    expected = {k: len(_distinct_keys(k, rows)) for k, rows in streams.items() if rows}

    # ── 2. Ingest through /v1/ingest-decoded ──────────────────────────────────
    body = {"device": {"id": DEVICE, "name": "e2e"}, "streams": streams}
    r = client.post("/v1/ingest-decoded", json=body)
    assert r.status_code == 200, r.text
    upserted = r.json()["upserted"]
    # The upsert reports the number of rows SUBMITTED per stream (== decoded list length);
    # same-key rows then collapse on insert. So reported >= distinct-keys persisted.
    for k, rows in streams.items():
        if rows:
            assert upserted[k] == len(rows), \
                f"upsert {k}: reported {upserted[k]} != submitted {len(rows)}"
            assert upserted[k] >= expected[k]

    # ── 3. Compute the spanned day(s) (ingest already triggered it; idempotent) ──
    for d in spanned:
        rc = client.post("/v1/compute-daily", json={"device": DEVICE, "date": d.isoformat()})
        assert rc.status_code == 200, rc.text

    # ── 4. Read + coherence: /v1/daily and /v1/sleep ──────────────────────────
    daily_rows = client.get(
        "/v1/daily", params={"device": DEVICE, "from": lo.isoformat(), "to": hi.isoformat()}
    ).json()
    assert isinstance(daily_rows, list)
    # Days with data may yield a row (if a sleep night ends that day) or none (a short
    # midday capture with no sleep). Whatever rows exist must be structurally coherent.
    for row in daily_rows:
        assert isinstance(row["day"], (_dt.date, str)), f"unexpected day type: {type(row['day'])}"
        if isinstance(row["day"], str):
            _dt.date.fromisoformat(row["day"])  # raises ValueError if malformed
        eff = row["efficiency"]
        assert eff is None or 0.0 <= eff <= 1.0, f"efficiency out of range: {eff}"
        rec = row["recovery"]
        assert rec is None or 0.0 <= rec <= 100.0, f"recovery out of range: {rec}"
        strain = row["strain"]
        assert strain is None or 0.0 <= strain <= 21.0, f"strain out of range: {strain}"
        rhr = row["resting_hr"]
        assert rhr is None or 25 <= rhr <= 120, f"resting_hr implausible: {rhr}"
        tsm = row["total_sleep_min"]
        assert tsm is None or tsm >= 0, f"negative total_sleep_min: {tsm}"
        # Calibrated nightly signals (Task 11a) — present + within physical bounds
        # (APPROXIMATE; may be None when the night lacked the source stream).
        for k in ("spo2_pct", "skin_temp_dev_c", "resp_rate_bpm"):
            assert k in row, f"missing new daily field {k}"
        sp = row["spo2_pct"]
        assert sp is None or 70.0 <= sp <= 100.0, f"spo2_pct out of range: {sp}"
        rrate = row["resp_rate_bpm"]
        assert rrate is None or 6.0 <= rrate <= 30.0, f"resp_rate_bpm out of range: {rrate}"

    for d in spanned:
        sleep = client.get("/v1/sleep", params={"device": DEVICE, "date": d.isoformat()}).json()
        assert isinstance(sleep, list), f"/v1/sleep did not return a list for {d}"
        # The capture is ~12 minutes — too short to be a sleep session, so the list is
        # expected to be empty. Do NOT require a session; assert coherence if one exists.
        for sess in sleep:
            assert isinstance(sess["stages"], list)
            start = sess["start_ts"]
            end = sess["end_ts"]
            assert start is not None and end is not None and str(end) >= str(start)
            se = sess["efficiency"]
            assert se is None or 0.0 <= se <= 1.0

    # ── 5. Reconciliation (no drop): /v1/summary counts == distinct decoded keys ──
    # "No drop" means every DISTINCT natural-key sample must be persisted. For streams
    # keyed on (device_id, ts) — spo2, skin_temp, resp, gravity — two decoded samples
    # sharing the same second collapse last-write-wins on upsert; that is a schema
    # property, not a drop. The `expected` dict is already computed from distinct keys,
    # so this assertion validates exactly what the DB durably stores.
    summary = client.get(
        "/v1/summary",
        params={"device": DEVICE, "from": 0, "to": 2_000_000_000},
    ).json()
    for k, n in expected.items():
        assert summary[k] == n, (
            f"RECONCILIATION MISMATCH for {k}: persisted {summary[k]} != "
            f"distinct decoded keys {n} (real drop/dup finding)")
    # Streams that decoded to nothing must be absent from the DB too.
    for k in ("events", "battery"):
        if k not in expected:
            assert summary[k] == 0

    # ── 6. Idempotency (no dup): re-ingest + re-compute changes nothing ───────
    r2 = client.post("/v1/ingest-decoded", json=body)
    assert r2.status_code == 200, r2.text
    summary2 = client.get(
        "/v1/summary",
        params={"device": DEVICE, "from": 0, "to": 2_000_000_000},
    ).json()
    assert summary2 == summary, f"re-ingest changed counts (dup!): {summary} -> {summary2}"

    for d in spanned:
        rc2 = client.post("/v1/compute-daily", json={"device": DEVICE, "date": d.isoformat()})
        assert rc2.status_code == 200, rc2.text

    # daily_metrics + sleep_sessions must not multiply across recomputes.
    with psycopg.connect(clean_db) as conn, conn.cursor() as cur:
        cur.execute("SELECT count(*) FROM daily_metrics WHERE device_id=%s", (DEVICE,))
        n_daily = cur.fetchone()[0]
        assert n_daily == len(daily_rows), (
            f"daily_metrics row count changed on recompute: {len(daily_rows)} -> {n_daily}")
        # one row per (device, day) at most — never duplicated.
        cur.execute(
            "SELECT day, count(*) FROM daily_metrics WHERE device_id=%s GROUP BY day", (DEVICE,))
        for day, cnt in cur.fetchall():
            assert cnt == 1, f"duplicate daily_metrics row for {day}: {cnt}"
